### ISSUE TITLE
Napredna analiza

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#10]
``` R
g <- ggplot(priseljenimoski, aes(x=leto, y=stevilka)) + geom_point()
print(g)

h<- g + geom_smooth(method = "lm")
print(h)

kv <- lm(data =priseljenimoski , stevilka ~ leto + I(leto^2))
kv <- g + geom_smooth(method = "lm", formula = y ~ x + I(x^2))
print(kv)
```

Katero funkcijo naj uporabim da bo najboljša napoved? Poskusila sem tudi s polinomi višje stopnje. 
Glede grupiranja podatkov: nevem točno katere podatke naj zgrupiram.

**Comment by jaanos** [comment]
Lahko poskusiš še z `loess` in `gam` (poglej si, kako smo to naredili na vajah).

Kar se grupiranja tiče, morda pri tebi to ni tako smiselno, saj imaš podatke po regijah, teh je pa dokaj malo. Lahko bi sicer poskusila zbrati podatke za vsako regijo po različnih kategorijah (vsak podatek v svojem stolpcu - torej ne v obliki tidy data), pa potem poskusila s kakšnim razvrščanjem na manjše število skupin. Ni pa nujno, da bi ti to razvrščanje pokazalo kaj pametnega.

**Comment by NabergojV** [comment]
Naredila sem tudi napoved z relaijo moski~zenske, ali je to smiselno?
Ali lahko karkoli zgrupiram pri tabeli tabela ali moram nujno uporabiti tabelo2 (regije)
Lahko tudi uvozim tabelo razdeljeno po občinah, če je to boljše za grupiranje podatkov.

**Comment by jaanos** [comment]
Morda napoved tukaj ni najbolj smiselna, je pa vsekakor zanimiv graf - seveda pa v poročilo napiši tudi interpretacijo tega grafa.

Kar se tiče grupiranja, je pa tako, da so podatki v `tabela2` v obliki, ki je bolj primerna za grupiranje. Svetujem sicer, da si izbereš samo eno leto in grupiranje narediš za podatke v tistem letu.

Če imaš podatke za občine, bi to vsekakor bilo bolj zanimivo, saj se morda lahko pokažejo kakšne podobnosti in razlike, ki jih razdelitev na statistične regije zabriše.

**Comment by NabergojV** [comment]
Uvozila sem tabelo za občine. Za grupiranje sem izbrala leto 2014. Ko poskušam zgrupirati podatke mi vrže tole napako:

``` R
Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning message:
In kmeans(podatki, 5) : NAs introduced by coercion
```

Koda je v `analiza.r` pod naslovom `# NAPREDNA ANALIZA z občinami:`

**Comment by jaanos** [comment]
`kmeans` izvedi na `podatki.normalizirani`. Poleg tega pri normalizaciji izpusti prvi stolpec (ime občin) - tega lahko dodaš kot imena vrstic:

``` R
podatki.normalizirani <- scale(podatki[-1])
names(podatki.normalizirani) <- podatki[,1]
k <- kmeans(podatki.normalizirani, 5)
```

**Comment by NabergojV** [comment]
Najlepša hvala za odgovor, vendar mi, ko hočem pogledati zemljevid, vrže to napako : 

``` R
Error in seq.default(h[1], h[2], length.out = n) : 
  'to' cannot be NA, NaN or infinite
```

**Comment by jaanos** [comment]
Najprej bo treba nastaviti ustrezno kodiranje znakov pri uvozu zemljevida - zemljevid občin uporablja `Windows-1250`. Nastavljanje imen vrstic sem napisal narobe - treba bo uporabiti funkcijo `row.names`:

``` R
row.names(podatki.normalizirani) <- podatki[,1]
```

Drugič, imena občin v podatkih se ne ujemajo povsem s tistimi iz zemljevida. Najlažje bo uporabiti funkcijo `preuredi`, ki jo imaš definirano v `uvozi.zemljevid.r`:

``` R
obcine$skupina <- factor(preuredi(k$cluster, obcine, "OB_UIME", novi = "Ankaran"))
```

Predhodno urejanje zemljevida tako niti ni potrebno, saj za to poskrbi `preuredi`. Zemljevid bi moral potem delovati.

**Comment by NabergojV** [comment]
Deluje! Najlepša hvala za vse odgovore!

**Comment by NabergojV** [comment]
Sedaj sem opazila, da pri `shiny8` (oziroma zemlejvidu občin) pri tistih letih, kjer so nekateri podatki NaN zemljevida noče izrisati i n vrže tole napako:

``` R
NA/NaN/Inf in foreign function call (arg 1)
```

**Comment by jaanos** [comment]
Najprej eno opozorilo: zemljevida ti ni treba vsakič znova nalagati znotraj Shinyja, saj potem ta deluje zelo počasi. Uporabiš lahko npr. zemljevid `obcine`, ki ga imaš iz `analiza.r`. Prav tako ni potrebno dvakrat klicati `kmeans`.

Trenutno sploh ne upoštevaš dobljene delitve v zemljevidu, saj spreminjaš zemljevid `obcina`, rišeš pa `slov`. Da ne bo potrebno vsakič klicati `pretvori.zemljevid`, si lahko izven `renderPlot` pripraviš razpredelnico `slov`, ki bo imela tudi ime občine iz podatkov:

``` R
  obc <- as.character(unique(tabelanapr2$občina))
  obcine$ime <- preuredi(setNames(obc, obc), obcine, "OB_UIME", novi = "Ankaran")
  slov <- pretvori.zemljevid(obcine)
```

Potem lahko izpustiš vrstice brez podatkov:

``` R
    podatki.normalizirani <- scale(podatki[c(-1, -2)]) # izpustimo še leto (2. stolpec)
    row.names(podatki.normalizirani) <- podatki[,1]
    podatki.na <- apply(podatki.normalizirani, 1, . %>% is.na() %>% all())
    podatki.normalizirani <- podatki.normalizirani[!podatki.na]
```

Po izračunu skupin jih lahko vneseš v zemljevid in tega narišeš:

``` R
    slov$skupina <- factor(k$cluster[slov$ime])
    ggplot(slov, aes(x=long, y=lat, group=group, fill=skupina)) + geom_polygon(color="grey55")
```

**Comment by NabergojV** [comment]
Najlepša hvala, deluje!
