### ISSUE TITLE
shiny

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#11]
Rada bi naredila shiny aplikacijo, ki bi mi izrisala graf za izbrano leto in izbran stolpec (priseljeni iz tujine moški,....). Ko zaženem aplikacijo mi vrne tole napako:

``` R
Listening on http://127.0.0.1:6616
Regions defined for each Polygons
Warning: Error in match: argument "colors" is missing, with no default
Stack trace (innermost first):
    52: match
    51: %in%
    50: col2rgb
    49: t
    48: colorRamp
    47: colorRampPalette
    46: do.call
    45: get(x, envir = this, inherits = inh)
    44: GeomPoint$new
    43: geom_point
    42: eval [analiza/analiza.r#31]
    41: eval
    40: withVisible
    39: source
    38: source
     1: shiny::runApp
Error in match(x, table, nomatch = 0L) : 
  argument "colors" is missing, with no default
```

**Comment by jaanos** [comment]
Napako ti javlja, ker v `analiza.r` kličeš funkcijo `colorRampPalette` brez argumentov. Če želiš zamenjati barvno lestvico, grafu prištej katero od funkcij `scale_color_*`, npr.

``` R
library(RColorBrewer)
h <- ggplot(priseljenispol, aes(x=zenske, y=moski,color=leto)) +
  geom_point(size=6) + scale_color_distiller(palette = "RdBu")
print(h)
```

Sicer pa ti svetujem, da ukaze `source` premakneš iz `server.R` v `shiny.r` (v vrhnjem imeniku projekta) in tega uporabljaš za poganjanje. Tako se ti ne bo celoten program še enkrat pognal, ko boš Shiny vključila v poročilo.

**Comment by NabergojV** [comment]
Upoštevala sem vse vaše rešitve. Zanima me še zakaj mi ne prikaže ggplot-a v shinyu, prikaže mi slider in radiobuttons, grafa pa ne.
Pa tudi če želim narediti aplikacijo še za zemljevide ter še eno za napredno analizo ali pišem vse v isto datoteko samo pod drug fluidPage? Kaj pa pri serverju? 
Najlepša hvala za odgovore.

**Comment by jaanos** [comment]
Grafa ti ne prikaže, ker v `ui.R` nimaš pravilno napisanega imena `"grafiregije"`.

Če hočeš še druge elemente v Shinyju, se moraš odločiti, kako želiš, da izgleda. Lahko enostavno namečeš elemente enega pod drugega, ali pa jih razporediš v zavihke (tako kot v vzorcu) - v obeh primerih imaš eno datoteko `ui.R` in eno `server.R`. Lahko pa seveda ločiš aplikacije, vsako v svojo mapo s svojim `ui.R` in `server.R`. Potem lahko vsako aplikacijo postaviš v poročilo na želeno mesto.

**Comment by NabergojV** [comment]
Najlepša hvala sem popravila, sedaj pa mi vrže napako pri argumentu `R podatek` : 

``` R
Listening on http://127.0.0.1:6621
Warning: Error in eval: object 'podatek' not found
Stack trace (innermost first):
    68: output$grafiregije
     1: runApp
```

**Comment by jaanos** [comment]
Meni sicer požene, a se podatki na grafu ne prikažejo, ker je `podatek` niz in ga `aes` ne razume kot ime stolpca. To lahko rešiš tako, da uporabiš `aes_string`, npr.

``` R
    ggplot(data=regijeleto,aes_string("regija", podatek))+ 
        geom_bar(stat="identity",fill="deeppink3",size=10)+
        coord_flip()
```

**Comment by NabergojV** [comment]
Hvala, sedaj deluje!
Ali Vas lahko prosim če preverite ali sem pravilno ustvarila novo mapo za novo shiny aplikacijo in ali sem pravilno kopirala obvezne elemente znotraj mape? 
Ko sem kopirala shiny aplikacijo v Rmarkdown mi je, ko sem poročilo zagnala odprlo okence, pri katerem sem morala potrditi da mi aplikacijo rendira (render) saj drugače ne bo delovala. Ali je to v redu ali sem narobe vstavila aplikacijo v poročilo?

**Comment by NabergojV** [comment]
Vidim, da sem mapo pravilno ustvarila. Sedaj me zanima za tretjo aplikacijo shiny, ko ustvarim novo mapo, ali lahko poimenujem dve datoteki ui in server npr: server2.r, ui2.r ? Brala sem, da mora biti končnica obvezno r, da potem program avtomatično prebere tisto datoteko.

**Comment by jaanos** [comment]
Imeni datotek v vsaki mapi za Shiny naj bosta `server.R` in `ui.R`. Tako ti trenutno `shiny` in `shiny2` delujeta, `shiny3` pa ne.

Celotne Shiny aplikacije ti ni treba kopirati v poročilo, pač pa jo lahko vključiš z ukazom

``` R
shinyAppDir("shiny", options=list(width="100%", height=460))
```

(podobno še za `"shiny2"` in `"shiny3"`). Ko te vpraša, ali naj požene Shiny, izberi kar _Yes, Always_, da ga bo potem vsakič pognalo (to bo dodalo še eno vrstico v glavo dokumenta).

Še to: v `analiza.r` se dvakrat sklicuješ na stolpec `državljanstvo`, razpredelnici `priseljeni` in `prinapr` pa imata ustrezen stolpec brez šumnika. Poleg tega premakni izrisovanje grafov iz `analiza.r` na ustrezno mesto v poročilo oziroma Shiny.

**Comment by NabergojV** [comment]
Ja, sem spremenila državljanstvo v drzavljanstvo in sem posodobila samo mapo uvoz, drugih pa še ne. Najlepša hvala za odgovore!!

**Comment by NabergojV** [comment]
Ko zaženem shiny za zemljevid mi vrže tole napako:
Kaj moram popraviti?

``` R
Listening on http://127.0.0.1:5525
Warning: Error in <-: object 'zeml' not found
Stack trace (innermost first):
    76: renderPlot [C:\Users\david\Documents\FAKS\ANALIZA PODATKOV S PROGRAMOM R\APPR-2015-16\shiny3/server.R#16]
    68: output$zemljevid
     1: runApp
```

**Comment by jaanos** [comment]
Nikjer ne definiraš spremenljivke `zeml` - najbrž hočeš uporabiti `zemljevid`?

Da ti ne bo pri vsakem izrisovanju zemljevida klicalo `pretvori.zemljevid` (kar vzame nekaj časa), svetujem, da si pripraviš pretvorjen zemljevid, potem pa ustrezne podatke pridružiš z `right_join`:

``` R
shinyServer(function(input, output){
  zeml <- pretvori.zemljevid(zemljevid)

  output$zemljevid <- renderPlot({

    letozem <- razberi(input$letoizberi,"leto",tabela2)

    končnipodatki <- letozem %>%
      right_join(zeml, by = c("regija" = "NAME_1")) %>%
      rename(priseljeni.skupaj = Priseljeni.iz.tujine.skupaj,
             priseljeni.iz.tujine.na.1000.prebivalcev = Priseljeni.iz.tujine.na.1000.prebivalcev,
             priseljeni.ženske = Priseljeni.iz.tujine.ženske,
             priseljeni.moški = Priseljeni.iz.tujine.moški,
             odseljeni.skupaj = Odseljeni.v.tujino.skupaj,
             odseljeni.ženske = Odseljeni.v.tujino.ženske,
             odseljeni.moški = Odseljeni.v.tujino.moški,
             odseljeni.v.tujino.na.1000.prebivalcev = Odseljeni.v.tujino.na.1000.prebivalcev)
    zeml$priseljeni.minus.odseljeni <-zeml$priseljeni.skupaj-zeml$odseljeni.skupaj

    ggplot() + geom_polygon(data = končnipodatki, 
                            aes_string(x="long", y="lat", group="group",
                            fill=input$priods),
                            color = "grey35") +
                            scale_fill_gradient(low="violetred4", high="violet")
 })
})
```

Zadnji stolpec bi sicer lahko dodala tudi z `mutate`, a v tem primeru ne bo delovalo, ker v zemljevidu že imaš stolpec z istim imenom (lahko bi ga prej pobrisala).

Da ti ne bo izpisovalo opozoril, lahko narediš še

``` R
tabela2$regija <- factor(tabela2$regija)
```

(najbolje kar tam, kjer definiraš `tabela2`).

**Comment by NabergojV** [comment]
Najlepša hvala, vse deluje!

**Comment by NabergojV** [comment]
Imam še eno vprašanje: pri zgornjem shinyu `R shiny3` sem dodala še 2 stolpca v tabelo: `R prirast ženske (prise.min.odse.z) , prirast moški (prise.min.odse.m)`. V poročilu se zemljevid za te dve kategoriji od začetnega ( pri letu 1995 ) ne spremeni nič ko spreminjam leta. Prav tako tudi pri `R prirast skupaj ( prise.min.odse.sku )`. Zanima me ali sem prav definirala dodatne stolpce v mapah `R shiny3` in `R vizualizacija` ali sem se zmotila in se zato zemljevidi ne spreminjajo ko se spreminajo leta.

**Comment by jaanos** [comment]
Zadnje tri stolpce hočeš definirati v razpredelnici `končnipodatki` - iz nje seveda tudi dobiš podatke, iz katerih te stolpce definiraš.

**Comment by NabergojV** [comment]
Najlepša hvala sem popravila!

**Comment by NabergojV** [comment]
Pardon ker ponovno sprašujem. Pri `shiny5`mi ko zaženem vrne graf obarvan glede na spol, namesto v samo dveh stolpcih (moški, ženske), vrne graf s presledki med ženskim in moškim odsekom. Pri spremenljivki državljanstvo vse deluje. Zanima me še kako bi lahko spremenila obarvanost (namesto roza in modre, karkoli drugega). Poskusila sem z `colorbrewerjem, scale_fill,` nič ni delovalo.

**Comment by NabergojV** [comment]
Šele sedaj sem opazila, da je pri `shiny2` pomešan vrstni red starostnih skupin, ki pa jih nisem na novo definirala. Starostna skupina `5-9 let` ni na drugem mestu kot bi morala biti pač pa pomešana med druge.

**Comment by NabergojV** [comment]
Pa še to: pri `shiny6` mi ne prikaže outputa, hkrati pa mi ne prikaže nobene napake. Kaj je narobe?

**Comment by jaanos** [comment]
Najprej: na koncu `uvoz.r` rišeš graf, ki ne deluje - namesto `geom_histogram` uporabi `geom_bar`. Seveda graf nariši na ustreznem mestu v poročilu, ne v `uvoz.r`. Isto naredi tudi v `shiny4`.

Pri `shiny5` se zgodi to, da v vsakem stolpcu nariše 4 kategorije (glede na spol in državljanstvo), barva pa glede na izbrano dimenzijo. Da bo lepo barvalo, bo treba podatke ustrezno združiti:

``` R
ggplot(data=tabelc %>% filter(spol!="Spol - SKUPAJ") %>%
             filter(drzavljanstvo != "Selitve - SKUPAJ") %>%
             group_by_("leto", input$držspol) %>%
             summarise(stevilo = sum(stevilka)),
           aes_string("leto","stevilo",fill=input$držspol))+ 
           geom_bar(stat="identity",size=4)
```

Tukaj `group_by_` deluje podobno kot `aes_string` (torej nize razume kot imena stolpcev).

Glede razvrstitve skupin pri `shiny2` bo najbolje, da na stolpcu `tabela$starostna.skupina` narediš urejen faktor - glede na to, da so v tabeli že po vrsti, lahko uporabiš kar ta vrstni red:

``` R
tabela$starostna.skupina <- factor(tabela$starostna.skupina,
                                   levels = unique(tabela$starostna.skupina),
                                   ordered = TRUE)
```

Najbolje, da to narediš tam, kjer definiraš razpredelnico `tabela`.

Pri `shiny6` imaš v `server.r` napačno napisano ime grafa. Poleg tega bo treba popraviti še ustvarjanje razpredelnice `priseljeniizb`.

**Comment by NabergojV** [comment]
Najlepša hvala za vse odgovore!! 
Probleme pri `shiny6` sem odpravila. Hvala še enkrat!
