### ISSUE TITLE
funkcija za filtriranje let, starostnih skupin...

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#4]
Rada bi funkcijo, ki bi mi filtrirala točno tisti podatek, ki ga želim; npr. leto 1995, starostna skupina 10-15 let,...

``` R
razberi <- function(x,y,podatki){
  razberix<-filter(podatki, y=="x")
  končna<-razberix[,-y]
  return(končna)
}
```

Potem pa mi izbriše tisti stolpec.. vrže mi tako napako:

``` R
> razberi(1995,leto,odseljeni)
 Show Traceback

 Rerun with Debug
 Error: comparison (1) is possible only for atomic and list types 
```

**Comment by jaanos** [comment]
dplyr uporablja posebne trike, da razume imena stolpcev v parametrih kot take in ne kot istoimenske spremenljivke - tako ne bo mogoče na enostaven način istega narediti za svoje funkcije. Poleg tega ti `"x"` lahko pomeni samo niz `'x'` in ne niza, odvisnega od spremenljivke `x` (tako bi lahko v `filter` uporabila kar `x`, če to ni tudi ime stolpca).

Brisanje z negacijo je možno samo za številske indekse (z dplyrjevo funkcijo `select` lahko sicer tako izpuščaš stolpce tudi po imenih, a bo znotraj funkcije isti problem kot prej), tako da bi tvoja funkcija lahko izgledala tako:

``` R
razberi <- function(x,y,podatki){
  return(podatki[podatki[y] == x, names(podatki) != y])
}
```

Potem moraš ime stolpca pri klicanju navesti kot niz:

``` R
razberi(1995, "leto", odseljeni)
```

Napako, kot jo dobiš, imaš verjetno zato, ker imaš definirano spremenljivko `leto`. Meni je seveda samo javilo, da `leto` ne obstaja.

**Comment by NabergojV** [comment]
Najlepša hvala in hvala tudi za hiter odgovor! Sedaj dela!

**Comment by NabergojV** [comment]
Želela bi sortirati tabelo padajoče po stolpcu: razlika skupaj. Poskusila sem z arrange, sort, order. Ali mi lahko prosim pomagate?

``` R
priseljeni.minus.odseljeni <- priseljeni.minus.odseljeni[order(priseljeni.minus.odseljeni$"razlika skupaj"),]
```

vrne pa mi tole napako:

``` R
Error in order(priseljeni.minus.odseljeni$"razlika skupaj") : 
  argument 1 is not a vector
```

**Comment by jaanos** [comment]
R pretvori presledke (in nekatere druge znake) v imenih stolpcev v pike, zato bo treba navesti ustrezno ime stolpca:

``` R
priseljeni.minus.odseljeni <- priseljeni.minus.odseljeni[order(priseljeni.minus.odseljeni$razlika.skupaj),]
```

Lahko pa uporabiš tudi funkcijo `arrange` iz knjižnice dplyr:

``` R
priseljeni.minus.odseljeni <- arrange(priseljeni.minus.odseljeni, razlika.skupaj)
```

**Comment by NabergojV** [comment]
spet najlepša hvala za čas in trud!
