### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [NabergojV/APPR-2015-16#6]
Poročila ti ne prevede, ker se v njem sklicuješ na spremenljivke iz vzorca. Najbolje bo, če del iz vzorca pobrišeš. Seveda bo potrebno dodati še kak graf iz tvojih podatkov.

**Comment by NabergojV** [comment]
To napako mi vrže ko hočem prevesti na Pdf

``` R
processing file: projekt.Rmd
Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label 'razpredelnice'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
```

**Comment by NabergojV** [comment]
sedaj mi vrže tole napako:

``` R
> source('~/.active-rstudio-document', encoding = 'UTF-8', echo=TRUE)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'C:/Users/david/Documents/.active-rstudio-document': No such file or directory
```

**Comment by jaanos** [comment]
Najprej, iz glave dokumenta odstrani vrstico `runtime: shiny`, da ti bo RStudio sploh omogočal prevajanje.

Do prve napake pride zato, ker imaš dva bloka kode z oznako `razpredelnice`. Ni potrebno, da ima vsak blok svojo oznako, obstoječe pa morajo biti različne.

Do nadaljnjih napak pride, ker še vedno vključuješ programa `vizualizacija.r` in `analiza.r`` iz vzorca. Če pobrišeš ustrezna bloka (pravzaprav lahko celo zadnje poglavje), bi ti moralo prevesti.

**Comment by NabergojV** [comment]
Sem uredila, še vedno pa mi vrže napako in sicer:

``` R
Quitting from lines 89-90 (projekt.Rmd) 
Error in is.vector(podatki) : object 'druzine' not found
Calls: <Anonymous> ... withVisible -> eval -> eval -> preuredi -> is.vector

Execution halted
```

**Comment by NabergojV** [comment]
opsa se opravičujem, dela! Najlepša hvala

**Comment by jaanos** [comment]
Bom dodal povezavo. Poročila mi sicer v PDF ne prevede, ga pa prevede v HTML.

Če boš še kaj spreminjala do predstavitve, mi prosim povej, da posodobim povezavo.
