### ISSUE TITLE
rmarkdown: ne pretvori v pdf obliko

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#7]
v html mi pretvori, v pdf pa ne. Domnevam da so problem šumniki, saj mi na računalniku na fakulteti ni hotelo pretvoriti niti v html.

**Comment by NabergojV** [comment]
Tole napako mi vrne:

``` R
output file: projekt.knit.md

This is XeTeX, Version 3.1415926-2.5-0.9999.3 (MiKTeX 2.9)
xelatex: The memory dump file could not be found.
xelatex: Data: xelatex.fmt

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
```

**Comment by jaanos** [comment]
Nisem pri svojem računalniku, tako da trenutno ne morem preveriti, a vidim dva problema:
- v `projekt.Rmd` je prišlo do konflikta: poišči vrstico `<<<<<<< HEAD` in pobriši neželene vrstice;
- v oznakah blokov naj ne bo presledkov: namesto `{r tabela 1}` in `{r tabela 2}` raje napiši `{r tabela1}` in `{r tabela2}`.

**Comment by jaanos** [comment]
Sem sedaj poskusil še pri sebi. Poleg zgornjih dveh problemov se napaka pojavi še pri drugem grafu - namesto `skupaj` želiš najbrž prikazati stolpec `stevilka`.

**Comment by NabergojV** [comment]
Sem popravila vse kar ste naročili, vendar še vedno ne prevede. Vrne mi sledečo napako:

``` R
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (MiKTeX 2.9)
xelatex: The memory dump file could not be found.
xelatex: Data: xelatex.fmt

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
```

**Comment by jaanos** [comment]
Meni deluje. Pri oznaki `tabela1` sicer pobriši presledek za oznako (torej `{r tabela1}`) - to sicer ne bi smelo vplivati za samo tabelo, a bi lahko povzročalo probleme pri grafih.

Sam sem opazil, da mi včasih prevajanje enkrat ne deluje, drugič pa - tako lahko še sama poskusiš še enkrat prevesti. Morda bo pomagalo tudi, če ponovno zaženeš RStudio.

**Comment by NabergojV** [comment]
Sem popravila, hvala!
