### ISSUE TITLE
zemljevidi

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#8]
Glede na to, da imam jaz Slovenijo razdeljeno po regijah in ne po občinah ter ne dobim zemljevida, oz takih podatkov z zemljepisnimi širinami kot so podatki _ob_, ali moram v podatke _ob_ dodati stolpec ki jih umesti v regijo in jih prek tega združim?  Stolpec _OB_ID_ ima zapisano številko občine in prek teh številk lahko združim v regije.

**Comment by jaanos** [comment]
To bi bila ena možnost, a bo najbrž lažje, če enostavno uporabiš zemljevid statističnih regij, kot ga dobiš na http://biogeo.ucdavis.edu/data/gadm2.8/shp/SVN_adm_shp.zip (zemljevid `SVN_adm1`). Pri uvozu tega zemljevida ne pozabi spremeniti kodiranja znakov na UTF-8.

Ta zemljevid za koordinate uporablja kar zemljepisno dolžino in širino, tako da lahko po potrebi podatke npr. o krajih dobiš tudi drugod.

**Comment by NabergojV** [comment]
Sem uvozila zemljevid, ampak mi vrže to napako, ko hočem zemljevid izrisati:

``` R
Error in pretvori.zemljevid(reg2014) : 
  trying to get slot "data" from an object (class "data.frame") that is not an S4 object 
```

**Comment by jaanos** [comment]
`reg2014` je razpredelnica, ki naj bi bila urejena tako kot zemljevid. Funkciji `pretvori.zemljevid` podaj zemljevid.

Najprej bo treba podati imena vrstic, da bo funkcija `preuredi` delovala pravilno:

``` R
rownames(regije2014) <- regije2014$regija
reg2014 <- preuredi(regije2014, zemljevid, "NAME_1")
```

Sedaj lahko skopiraš podatke iz `reg2014` v `zemljevid` in tega pretvoriš, npr.

``` R
zemljevid$priseljeni <- reg2014$Priseljeni.iz.tujine.skupaj
reg14 <- pretvori.zemljevid(zemljevid)
```

Seveda lahko skopiraš tudi več stolpcev.

**Comment by NabergojV** [comment]
Najlepša hvala, vse funkcionira!
