### ISSUE TITLE
predstavitev

### ISSUE THREAD

**Issue by NabergojV** [NabergojV/APPR-2015-16#9]
Dodala sem še nekaj detajlov. Prosim da posodobite mojo predstavitev.
Najlepša hvala.

**Comment by jaanos** [comment]
V redu, bom posodobil.

**Comment by jaanos** [comment]
Eno pripombo imam edino: da se ti poročilo prevede v PDF, v oznakah blokov kode ne sme biti pik. Svetujem torej, da namesto `zemljevid1.2` in `zemljevid2.2` raje uporabiš `zemljevid1_2` in `zemljevid2_2`.
